### ISSUE TITLE
logfile for bsmtp

### ISSUE THREAD

**Issue by abcnorio** [btactic/bsmtp#5]
Which logfile(s) log(s) activities of bsmtp to observe that the external smtp works properly or in case of problems to find out what went wrong while sending mails via bsmtp?

thanks and best
leo

**Comment by adriangibanelbtactic** [comment]
There are not log files implemented. If there are any errors the user is informed about an error having happened.

I recommend you to check the errors on the third-party smtp server logs.

Else patches are welcomed.
